# Core Fundamentals of NumPy

This notebook covers the essential building blocks of NumPy, including how to create arrays, use built-in functions for array generation, and understand fundamental array attributes.

### 1. Importing NumPy

As a standard convention, we import NumPy with the alias `np`.

In [1]:
import numpy as np

### 2. Creating a 1D Array

A 1D array, or vector, can be created by passing a Python list to the `np.array()` function.

In [2]:
l1 = [1,2,3,4,5]
arr1 = np.array(l1)
print(arr1)

[1 2 3 4 5]


### 3. Creating a 2D Array (Matrix)

A 2D array, or matrix, is created by passing a list of lists to `np.array()`.

In [3]:
l2 = [[1,2],[3,4]]
arr2 = np.array(l2)
print(arr2)

[[1 2]
 [3 4]]


### 4. Creating an Array with a Sequence

The `np.arange(start, stop)` function generates an array with evenly spaced values within a given interval. Note that the `stop` value is exclusive.

In [4]:
seq_arr = np.arange(0,10)
print(seq_arr)

[0 1 2 3 4 5 6 7 8 9]


### 5. Creating a Sequence with a Step

You can add a third argument, `step`, to `np.arange(start, stop, step)` to specify the increment between values.

In [5]:
seq_arr_step = np.arange(1,20,2)
print(seq_arr_step)

[ 1  3  5  7  9 11 13 15 17 19]


### 6. Creating an Array of Zeros

`np.zeros(shape)` creates an array of a specified shape, filled entirely with zeros. This is useful for initializing an array before populating it with data.

In [6]:
zero = np.zeros((3,3))
print(zero)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


### 7. Creating an Array of Ones

Similarly, `np.ones(shape)` creates an array filled with ones.

In [7]:
one = np.ones((3,4))
print(one)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


### 8. Creating an Array with `linspace`

`np.linspace(start, stop, num)` creates an array with a specified number (`num`) of evenly spaced points between a `start` and `stop` value (inclusive).

In [8]:
linespace = np.linspace(0,100,5)
print(linespace)

[  0.  25.  50.  75. 100.]


### 9. Generating a Random Array (Uniform Distribution)

`np.random.rand(rows, cols)` generates an array of a given shape with random values from a uniform distribution over `[0, 1)`.

In [9]:
ran_arr = np.random.rand(2,3)
print(ran_arr)

[[0.90499597 0.9827724  0.75087568]
 [0.92127522 0.47749668 0.97848699]]


### 10. Generating a Random Array (Standard Normal Distribution)

`np.random.randn(rows, cols)` generates an array with samples from the standard normal (or Gaussian) distribution, which has a mean of 0 and a standard deviation of 1.

In [10]:
ran_arr_2 = np.random.randn(3,2)
print(ran_arr_2)

[[-0.44911421  0.67343914]
 [-1.16485682  0.10000101]
 [ 2.56541691  0.13380793]]


### 11. Generating an Array of Random Integers

`np.random.randint(low, high, size)` creates an array of a specified size with random integers between a `low` (inclusive) and `high` (exclusive) value.

In [11]:
ran_arr_3 = np.random.randint(0,100,5)
print(ran_arr_3)

[15 66 28 15 84]


### 12. Understanding Array Data Types (`dtype`)

NumPy automatically infers the data type of an array's elements. You can check this with the `.dtype` attribute. Here, it correctly identifies the elements as 64-bit integers.

In [12]:
int_arr = np.array([1,2,3])
print(int_arr.dtype)

int64


For an array with floating-point numbers, the `dtype` will be `float64`.

In [13]:
int_arr_2 = np.array([1.1,1.2,1.3])
print(int_arr_2.dtype)

float64


You can also explicitly set the data type during creation using the `dtype` argument. This can be useful for optimizing memory usage.

In [14]:
int_arr = np.array([1,2,3], dtype='float32')
print(int_arr.dtype)

float32


### 13. Essential Array Attributes

NumPy arrays have several key attributes that provide metadata about their structure.
- **`.ndim`**: The number of dimensions (or axes) of the array.
- **`.shape`**: A tuple representing the size of the array in each dimension.
- **`.size`**: The total number of elements in the array.

In [15]:
attr_arr = np.zeros((2,4,3))
print(attr_arr)
print(attr_arr.ndim)
print(attr_arr.shape)
print(attr_arr.size)

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]
3
(2, 4, 3)
24
