# NumPy Array Indexing and Slicing

This notebook demonstrates how to access, select, and filter elements within NumPy arrays. We will cover basic indexing, slicing, and conditional selection.

In [1]:
import numpy as np

### 1. Creating Sample Arrays

Let's start by creating a 1D and a 2D array to use for our indexing and slicing examples.

A simple 1D array (vector) from 0 to 10.

In [ ]:
arr_1d = np.arange(0,11)
print(arr_1d)

[ 0  1  2  3  4  5  6  7  8  9 10]


A 5x5 2D array (matrix) with values from 0 to 24.

In [ ]:
arr_2d = np.arange(0,25).reshape(5,5)
print(arr_2d)


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


### 2. Basic Indexing

Indexing in NumPy is similar to Python lists. You can access elements using square brackets `[]`.

Accessing an element in a 1D array is straightforward. Here, we get the element at index 3.

In [ ]:
print(arr_1d[3])

3


Negative indexing allows you to access elements from the end of the array. `-1` refers to the last element.

In [ ]:
print(arr_1d[-1])

10


For a 2D array, you use the format `[row, column]` to access a specific element. Here, we get the element at the first row and first column.

In [ ]:
print(arr_2d[0,0])

0


Accessing the element at the 3rd row (index 2) and 4th column (index 3).

In [7]:
print(arr_2d[2,3])

13


### 3. Slicing

Slicing lets you extract a subset of an array. The syntax is `[start:stop:step]`, where `stop` is exclusive.

Here, we slice the 1D array from index 2 up to (but not including) index 6.

In [ ]:
slice_arr_1d = arr_1d[2:6]
print(slice_arr_1d)

[2 3 4 5]


To slice a 2D array, you specify the slice for both the rows and columns. This example extracts the first two rows and all columns. The `:` by itself means "select all".

In [ ]:
print(arr_2d[0:2, :])

[[0 1 2 3 4]
 [5 6 7 8 9]]


This extracts all rows but only the columns from index 2 up to index 4.

In [ ]:
print(arr_2d[:,2:4])

[[ 2  3]
 [ 7  8]
 [12 13]
 [17 18]
 [22 23]]


You can combine row and column slicing to extract a specific sub-matrix. This code selects a 2x2 matrix from the top-right corner.

In [ ]:
print(arr_2d[0:2,3:5])

[[3 4]
 [8 9]]


### 4. Boolean Indexing (Conditional Selection)

This powerful feature allows you to select elements from an array based on a condition.

First, we create a boolean "mask" by applying a condition to the array. The resulting array contains `True` where the condition is met and `False` otherwise.

In [ ]:
bool_mask = arr_2d > 15
print(bool_mask)

[[False False False False False]
 [False False False False False]
 [False False False False False]
 [False  True  True  True  True]
 [ True  True  True  True  True]]


By passing this boolean mask back into the array, we can select only the elements that correspond to `True` values.

In [ ]:
sel_data = arr_2d[bool_mask]
print(sel_data)

[16 17 18 19 20 21 22 23 24]


You can combine the condition and selection into a single, concise line.

In [ ]:
selected_data_oneline = arr_2d[arr_2d > 15]
print(selected_data_oneline)

[16 17 18 19 20 21 22 23 24]


Here's another example: selecting all even numbers from the array.

In [ ]:
print(arr_2d[arr_2d % 2 ==0])

[ 0  2  4  6  8 10 12 14 16 18 20 22 24]


### 5. Views vs. Copies: A Critical Concept

By default, slices of a NumPy array are **views**, not copies. This means they point to the same underlying data in memory. Modifying a view will also modify the original array.

Let's create a slice containing the first row of our 2D array.

In [ ]:
row_0 = arr_2d[0,:]
print(row_0)

[0 1 2 3 4]


To prevent this behavior and create an independent copy of the array, use the `.copy()` method.

In [ ]:
arr_2d_copy = arr_2d.copy()
print(arr_2d_copy)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


Now, let's modify the first element of our `row_0` slice. Because `row_0` is a view, the change is reflected in the original `arr_2d`. However, `arr_2d_copy` remains unchanged because it's a separate copy.

In [ ]:
row_0[0] = 100
print(row_0)
print(arr_2d)
print(arr_2d_copy)

[100   1   2   3   4]
[[100   1   2   3   4]
 [  5   6   7   8   9]
 [ 10  11  12  13  14]
 [ 15  16  17  18  19]
 [ 20  21  22  23  24]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
