# Array Manipulation and Shaping

This notebook covers essential techniques for changing the shape and structure of NumPy arrays, including reshaping, transposing, flattening, and combining arrays.

In [1]:
import numpy as np

### 1. Reshaping Arrays

Reshaping allows you to change the dimensions of an array without changing its data.

First, let's create a 1D array with 12 elements.

In [2]:
arr = np.arange(12)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


The `.reshape(rows, cols)` method converts the 1D array into a 2D matrix. The total number of elements must remain the same (3 * 4 = 12).

In [ ]:
matrix_3X4 = arr.reshape(3,4)
print(matrix_3X4)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


We can reshape it into a 4x3 matrix as well.

In [ ]:
matrix_4X3 = arr.reshape(4,3)
print(matrix_4X3)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


You can use `-1` in one of the dimensions, and NumPy will automatically calculate the correct value based on the array's size. This is very convenient when you don't want to calculate the dimension yourself.

In [ ]:
matrix_auto = arr.reshape(2,-1)
print(matrix_auto)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


### 2. Transposing Arrays

Transposing swaps the rows and columns of a matrix. It can be done using the `.T` attribute.

The original 3x4 matrix is transformed into a 4x3 matrix where the rows become columns and vice versa.

In [6]:
print(matrix_3X4)
matrix_3X4_T = matrix_3X4.T
print(matrix_3X4_T)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


### 3. Flattening Arrays

Flattening converts a multi-dimensional array into a 1D array.

The `.flatten()` method returns a 1D **copy** of the array.

In [7]:
flattened_arr = matrix_3X4.flatten()
print(flattened_arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


The `.ravel()` method also returns a 1D array, but it may return a **view** of the original array if possible. This makes it faster and more memory-efficient.

In [8]:
raveled_arr = matrix_3X4.ravel()
print(raveled_arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


**Key Difference:** `flatten()` always returns a copy, meaning changes to the new array won't affect the original. `ravel()` returns a view when possible, so modifications might alter the original array. Use `flatten()` if you need to be sure the original array is safe.

### 4. Combining Arrays: Concatenating and Stacking

NumPy provides several ways to join arrays together.

Let's create two sample 2x2 arrays.

In [9]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
print(a)
print(b)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


#### Concatenate

`np.concatenate()` joins a sequence of arrays along a specified axis.
- `axis=0` concatenates along the rows (stacking them vertically).
- `axis=1` concatenates along the columns (placing them side-by-side).

In [ ]:
concatenated_rows = np.concatenate([a,b], axis=0)
print(concatenated_rows)
concatenated_col = np.concatenate([a,b], axis=1)
print(concatenated_col)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


#### Stacking

Stacking functions provide a more convenient syntax for concatenation.
- `np.vstack()` (vertical stack) is equivalent to `concatenate` with `axis=0`.
- `np.hstack()` (horizontal stack) is equivalent to `concatenate` with `axis=1`.

In [ ]:
v_stack = np.vstack([a,b])
h_stack = np.hstack([a,b])
print(v_stack)
print(h_stack)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]
