# Broadcasting and Linear Algebra

This notebook covers two advanced but crucial NumPy topics: broadcasting, which allows operations on arrays of different shapes, and fundamental linear algebra operations.

In [1]:
import numpy as np

### 1. Broadcasting

Broadcasting describes the rules for how NumPy handles operations between arrays of different but compatible shapes. It avoids the need to create explicit copies of data, making code more efficient.

#### A Simple Example
The simplest case of broadcasting occurs when combining an array with a scalar (a single number). The scalar is "broadcast" or stretched to match the shape of the array, and the operation is performed element-wise.

In [2]:
arr = np.array([0,1,2])
print(arr)

result = arr + 5
print(result)

[0 1 2]
[5 6 7]


#### A More Practical Use Case
A common use case is centering data by subtracting the mean of each feature (column).
1. We create a 3x4 data matrix.
2. We calculate the sum of each column (`axis=0`).
3. Broadcasting allows us to directly subtract the 1D `col_sum` array from the 2D `data` array. NumPy automatically "stretches" the row vector `[12, 15, 18, 21]` to match the shape of the data, subtracting it from each of the three rows.

In [3]:
data = np.arange(12).reshape(3,4)
print(data)

col_sum = data.sum(axis=0)
print(col_sum)

normalized = data - col_sum
print(normalized)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[12 15 18 21]
[[-12 -14 -16 -18]
 [ -8 -10 -12 -14]
 [ -4  -6  -8 -10]]


Here is another clear example. We subtract a 1D array of column means from a 2D data matrix. The `col_means` vector (shape `(4,)`) is broadcast across each of the three rows of the `data` matrix (shape `(3, 4)`).

In [4]:
# A 3x4 data matrix
data = np.arange(12).reshape(3, 4)
print(f"Data matrix (3x4):\n{data}")

# Let's say we have the means of each column
# This is a 1D array (vector) of shape (4,)
col_means = np.array([10, 20, 30, 40])
print(f"\nColumn means (shape {col_means.shape}): {col_means}")

# We can directly subtract the means from the data matrix!
# NumPy broadcasts the `col_means` vector to each of the 3 rows.
normalized_data = data - col_means
print(f"\nNormalized data (data - col_means):\n{normalized_data}")

Data matrix (3x4):
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Column means (shape (4,)): [10 20 30 40]

Normalized data (data - col_means):
[[-10 -19 -28 -37]
 [ -6 -15 -24 -33]
 [ -2 -11 -20 -29]]


### 2. Introduction to Linear Algebra

NumPy is a powerhouse for linear algebra. The `numpy.linalg` submodule contains a wide range of functions.

#### Element-wise vs. Matrix Multiplication
It's critical to distinguish between the two types of multiplication:
- `*` performs **element-wise** multiplication.
- `@` (or `np.dot()`) performs **matrix** multiplication (the dot product).

In [5]:
A = np.array([[1,2],
              [3,4]])
B = np.ones((2,2), dtype=int)

print(A)
print(B)

# *
print(A*B)

# @
print(A @ B)

[[1 2]
 [3 4]]
[[1 1]
 [1 1]]
[[1 2]
 [3 4]]
[[3 3]
 [7 7]]


### 3. Matrix Inverse

The inverse of a matrix `A` is a matrix `A_inv` such that their product is the identity matrix. We can compute it using `inv()` from the `numpy.linalg` submodule.

Let's import the necessary functions from `numpy.linalg`.

In [6]:
from numpy.linalg import inv, det, eig

Here we compute the inverse of matrix `A`.

In [7]:
A_inv = inv(A)
print(A)
print(A_inv)

[[1 2]
 [3 4]]
[[-2.   1. ]
 [ 1.5 -0.5]]


To verify, we can multiply `A` by its inverse. The result is the identity matrix (with a very small floating-point error).

In [8]:
identity = A @ A_inv
print(identity)

[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


### 4. Determinant

The determinant is a scalar value that can be computed from a square matrix. We use the `det()` function.

In [9]:
A_det = det(A)
print(A_det)

-2.0000000000000004


### 5. Eigenvalues and Eigenvectors

The `eig()` function computes the eigenvalues and eigenvectors of a square matrix. It returns a tuple containing an array of eigenvalues and a matrix of corresponding eigenvectors.

In [10]:
A_eig = eig(A)
print(A_eig)

EigResult(eigenvalues=array([-0.37228132,  5.37228132]), eigenvectors=array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))
